#!/bin/sh

scriptdir="$(dirname "$(readlink -f $0)")";

cd "$scriptdir/..";
export RDBASE="$(pwd)";
export LD_LIBRARY_PATH="$(pwd)/lib");
export PYTHONPATH="$(pwd)/lib");

mkdir build;
cd build;
    
cmake -DRDK_BUILD_INCHI_SUPPORT=ON -D PYTHON_LIBRARY=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5.so -D PYTHON_INCLUDE_DIR=/usr/include/python3.5/ -D PYTHON_EXECUTABLE=/usr/bin/python3.5 -DBOOST_LIBRARY_DIR=/usr/include/boost/ ..;

make install
unset LD_LIBRARY_PATH;
unset RDBASE;
unset PYTHONPATH;
